silau/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from silau_app.forms import AuthenticationForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(authentication_form=AuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('testimoni/', include('testimoni.urls')),
    path('topup/', include('topup.urls')),
    path('laundry/', include('laundry.urls')),
    path('', include('silau_app.urls'))
]

testimoni/urls.py
from django.urls import path
from .views import *

app_name = 'testimoni'

urlpatterns = [
    path('<int:page>/', index, name='index'),
    path('other/<int:page>/', other, name='other'),
    path('add/', add, name='add'),
    path('update/<str:email>/<str:tanggal_testimoni>/<str:tanggal_transaksi>/', update, name='update'),
    path('datechoices/', datechoices, name='datechoices'),
    path('deletetestimoni/<int:page>/<str:email>/<str:tanggal_testimoni>/<str:tanggal_transaksi>/', deletetestimoni, name='deletetestimoni')
]

testimoni/models.py
from django.db import models

# Create your models here.

testimoni/forms.py
from django import forms
from django.db import connection
import datetime
from django.core.exceptions import ValidationError

class AddForm(forms.Form):
  cursor = connection.cursor()
  cursor.execute('SELECT email, email FROM EMAIL_PELANGGAN()')
  row = cursor.fetchall()
  EMAIL_CHOICES = row

  TANGGAL_CHOICES = []

  email = forms.EmailField(max_length=50, widget=forms.Select(choices = EMAIL_CHOICES))
  tanggal = forms.DateTimeField(widget=forms.Select(choices = TANGGAL_CHOICES))
  status = forms.CharField()
  rating = forms.IntegerField()

  def save(self):
    cd = self.cleaned_data
    now = str(datetime.datetime.now())
    tge = str(cd['tanggal'])
    rt = str(cd['rating'])

    cursor = connection.cursor()

    try:
      cursor.execute(
        "INSERT INTO TESTIMONI VALUES('"
        + cd['email'] + "','"
        + tge + "','"
        + now + "','"
        + cd['status'] + "','"
        + rt + "')"
      )
    except Exception as e:
      self.add_error(None, e)

class UpdateForm(forms.Form):
  email = forms.EmailField(max_length=50, widget=forms.EmailInput(attrs={'readonly':'readonly'}))
  tanggal_transaksi = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'readonly':'readonly'}))
  tanggal_testimoni = forms.DateTimeField(widget=forms.HiddenInput)
  status = forms.CharField()
  rating = forms.IntegerField()

  def save(self):
    cd = self.cleaned_data
    now = str(datetime.datetime.now())
    tt = str(cd['tanggal_transaksi'])
    tteo = str(cd['tanggal_testimoni'])
    rt = str(cd['rating'])

    cursor = connection.cursor()

    try:
      cursor.execute(
        "UPDATE TESTIMONI SET tanggal_testimoni = '" + now + "', status = '" + cd['status'] + "', rating = '" + rt
        + "' WHERE email='" + cd['email']
		    + "' AND tanggal_testimoni='" + tteo
		    + "' AND tanggal_transaksi='" + tt + "'"
      )
    except Exception as e:
      self.add_error(None, e)

testimoni/views.py
from django.shortcuts import render
from .forms import *
from django.db import connection
from django.shortcuts import redirect
from django.http import JsonResponse, HttpResponseForbidden

datas = [
	{
		'email': 'lauren93@gmail.com',
		'tanggal_transaksi': '1949-08-28 00:00:00',
		'tanggal_testimoni': '1925-07-22 00:00:00',
		'status': 'a',
		'rating': 1
	},

	{
		'email': 'rachel77@phillips.com',
		'tanggal_transaksi': '1912-01-31 00:00:00',
		'tanggal_testimoni': '1966-05-13 00:00:00',
		'status': 'a',
		'rating': 2
	},

	{
		'email': 'ryanbailey@boyd.com',
		'tanggal_transaksi': '1936-02-03 00:00:00',
		'tanggal_testimoni': '2018-06-04 00:00:00',
		'status': 'a',
		'rating': 6
	},

	{
		'email': 'ismith@jones.com',
		'tanggal_transaksi': '1979-06-01 00:00:00',
		'tanggal_testimoni': '1928-12-03 00:00:00',
		'status': 'a',
		'rating': 7
	},

	{
		'email': 'amanda02@snow.net',
		'tanggal_transaksi': '1951-07-15 00:00:00',
		'tanggal_testimoni': '1996-11-30 00:00:00',
		'status': 'n',
		'rating': 6
	}
]


# Create your views here.
def index(request, page):
	if not request.session.get('pengguna'):
		return HttpResponseForbidden()
	elif not request.session['pengguna']['is_pelanggan']:
		return HttpResponseForbidden()

	email = request.session['pengguna']['email']
	cursor = connection.cursor()
	offset = str(page * 10)
	cursor.execute("SELECT * FROM TESTIMONI WHERE email = '" + email +"' LIMIT 10 OFFSET " + offset)
	row = cursor.fetchall()

	response = {
		'isPelanggan': True,
		'datas': row,
		'cp' : page,
		'pp' : page - 1,
		'np' : page + 1
	}

	return render(request, "testimoni/read.html", response)

def other(request, page):
	cursor = connection.cursor()
	offset = str(page * 10)
	cursor.execute("SELECT * FROM TESTIMONI LIMIT 10 OFFSET " + offset)
	row = cursor.fetchall()
	
	response = {
		'input_form': UpdateForm(),
		'isPelanggan': False,
		'datas': row,
		'cp' : page,
		'pp' : page - 1,
		'np' : page + 1
	}

	return render(request, "testimoni/read.html", response)


def add(request):
	if not request.session.get('pengguna'):
		return HttpResponseForbidden()
	elif not request.session['pengguna']['is_pelanggan']:
		return HttpResponseForbidden()

	message = ''

	if(request.method == 'POST'):
		form = AddForm(request.POST)
		if(form.is_valid()):
			form.save()
			cd = form.cleaned_data
			if(cd['email'] != request.session['pengguna']['email']):
				form.add_error('email', 'Email harus sama dengan email login')
			if not form.errors:
				message = 'Testimoni berhasil ditambahkan'
				request.COOKIES['message'] = message
				return index(request, 0)
	else:
		form = AddForm()

	response = {
		'input_form': form,
		'message' : message
	}

	return render(request, "testimoni/add.html", response)


def update(request, email, tanggal_testimoni, tanggal_transaksi):
	if not request.session.get('pengguna'):
		return HttpResponseForbidden()
	elif not request.session['pengguna']['is_pelanggan']:
		return HttpResponseForbidden()

	message = ''

	if(request.method == 'POST'):
		form = UpdateForm(request.POST)
		if(form.is_valid()):
			form.save()
			if not form.errors:
				message = 'Testimoni berhasil diupdate'
				request.COOKIES['message'] = message
				return index(request, 0)
	else:
		cursor = connection.cursor()
		cursor.execute(
			"SELECT * FROM TESTIMONI WHERE email='" + email 
			+ "' AND tanggal_testimoni='" + tanggal_testimoni 
			+ "' AND tanggal_transaksi='" + tanggal_transaksi + "'"
			)
		row = cursor.fetchone()
		form = UpdateForm(initial={
			'email' : row[0],
			'tanggal_testimoni' : row[2],
			'tanggal_transaksi' : row[1],
			'status' : row[3],
			'rating' : row[4]
		})

	response = {
		'input_form': form,
		'message' : message
	}

	return render(request, "testimoni/update.html", response)

def datechoices(request):
	email = request.GET.get('email', '')
	cursor = connection.cursor()
	cursor.execute(
		"SELECT tanggal,tanggal FROM TANGGAL_TRANSAKSI('" + email +"')"
	)
	row = cursor.fetchall()
	json = {'dates' : row}
	return JsonResponse(json)

def deletetestimoni(request, page, email, tanggal_testimoni, tanggal_transaksi):
	if not request.session.get('pengguna'):
		return HttpResponseForbidden()
	elif not request.session['pengguna']['is_pelanggan']:
		return HttpResponseForbidden()
	
	message = ''
	cursor = connection.cursor()
	try:
		cursor.execute(
			"DELETE FROM TESTIMONI WHERE email='" + email 
			+ "' AND tanggal_testimoni='" + tanggal_testimoni 
			+ "' AND tanggal_transaksi='" + tanggal_transaksi + "'"
		)
		message = 'Testimoni berhasil dihapus'
	except Exception as e:
		message = e

	request.COOKIES['message'] = message
	return index(request, page)

testimoni/templates/testimoni/add.html
{% extends 'base.html' %}

{% block content %}
<h1> Add Testimoni </h1>
<form method="POST">
    {% csrf_token %}
    {{ input_form.as_p }}
    <input type="submit" value="Add" class="btn btn-warning">
</form>
{{message}}
{% endblock %}

{% block js %}
<script>
    $(document).ready(function(){
        var dateChoices = $('#id_tanggal');
        var emailChoices = $('#id_email');

        var setDateChoices = function(email){
            $.ajax({
                url: '/testimoni/datechoices',
                data:{'email' : email},
                dataType: 'json',
                success: function(response){
                    var dates = response['dates'];
                    for(date of dates){
                        dateChoices.append(
                            "<option value='" + date[0] + "'>" + date[1] +"</option>"
                        );
                    }
                }
            });
        }

        var emailc = emailChoices.val();
        dateChoices.empty();
        setDateChoices(emailc);
    
        emailChoices.change(function(){
            var emailc = emailChoices.val();
            dateChoices.empty();
            setDateChoices(emailc);
        })
    })
</script>
{% endblock %}

testimoni/templates/testimoni/read.html
{% extends 'base.html' %}

{% block content %}
<h1> Testimoni </h1>
{{request.COOKIES.message}}
<table class="table">
    <thead>
      <tr>
        {% if not isPelanggan %}
        <th scope="col">Email</th>
        {% endif %}
        <th scope="col">Tanggal Transaksi</th>
        <th scope="col">Tanggal Testimoni</th>
        <th scope="col">Status</th>
        <th scope="col">Rating</th>
        {% if isPelanggan %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
    {% for data in datas %}
      <tr>
        {% if not isPelanggan %}
        <td scope="col">{{data.0}}</td>
        {% endif %}
        <td scope="col">{{data.1}}</td>
        <td scope="col">{{data.2}}</td>
        <td scope="col">{{data.3}}</td>
        <td scope="col">{{data.4}}</td>
        {% if isPelanggan %}
        <td scope="col">
          <a href="{% url 'testimoni:update' email=data.0 tanggal_testimoni=data.2 tanggal_transaksi=data.1%}"><button>Update</button></a>
          <a href="{% url 'testimoni:deletetestimoni' page=cp email=data.0 tanggal_testimoni=data.2 tanggal_transaksi=data.1%}"><button>Hapus</button></a>
        </td>
        {% endif %}
      </tr>
    {% endfor %}
    </tbody>
</table>
<div>
  {% if isPelanggan %}
    {% if pp >= 0 %}<a href="{% url 'testimoni:index' page=pp %}"><button> &lt </button></a>{% endif%}
    Page {{cp}}
    {% if datas|length == 10 %} <a href="{% url 'testimoni:index' page=np %}"><button> &gt </button></a> {% endif %}
  {% else %}
    {% if pp >= 0 %}<a href="{% url 'testimoni:other' page=pp %}"><button> &lt </button></a>{% endif%}
    Page {{cp}}
    {% if datas|length == 10 %} <a href="{% url 'testimoni:other' page=np %}"><button> &gt </button></a> {% endif %}
  {% endif %}
</div>
{% endblock %}

testimoni/templates/testimoni/update.html
{% extends 'base.html' %}

{% block content %}
<h1> Update Testimoni </h1>
<form method="POST">
    {% csrf_token %}
    {{ input_form.as_p }}
    <input type="submit" value="Update" class="btn btn-warning">
</form>
{{message}}
{% endblock %}