silau/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from silau_app.forms import AuthenticationForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(authentication_form=AuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('testimoni/', include('testimoni.urls')),
    path('topup/', include('topup.urls')),
    path('laundry/', include('laundry.urls')),
    path('', include('silau_app.urls'))
]

silau_app/urls.py
from django.urls import path
from .views import *

app_name = 'silau'

urlpatterns = [
    path('', index, name='index'),
    path('login2/', login, name='login2'),
    path('logout2/', logout, name='logout2'),
    path('register/staff2/', register_staff, name='register_staff2'),
    path('register/courier2/', register_courier, name='register_courier2'),
    path('register/staff/', register_staff, name='register_staff'),
    path('register/courier/', register_courier, name='register_staff'),
    path('register/customer/', register_customer, name='register_customer')
]

testimoni/urls.py
from django.urls import path
from .views import *

app_name = 'testimoni'

urlpatterns = [
    path('<int:page>/', index, name='index'),
    path('other/<int:page>/', other, name='other'),
    path('add/', add, name='add'),
    path('update/<str:email>/<str:tanggal_testimoni>/<str:tanggal_transaksi>/', update, name='update'),
    path('datechoices/', datechoices, name='datechoices'),
    path('deletetestimoni/<int:page>/<str:email>/<str:tanggal_testimoni>/<str:tanggal_transaksi>/', deletetestimoni, name='deletetestimoni')
]

templates/base.html
<!DOCTYPE html>
<html>
  {# Make modifiable head elements #}
  <head>
    <title>
      {% block title %}Home {% endblock title %} | TK 2 Basdat Kel 16
    </title>
    {% block head_favicon %}
    <link
      rel="icon"
      type="image/png"
      href="{{ STATIC_URL }}images/favicon.ico"
    />
    {% endblock head_favicon %} {% block head_meta %} {% block head_meta_charset %}
    <meta charset="utf-8" />
    {% endblock head_meta_charset %} {% block head_meta_viewport %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% endblock head_meta_viewport %} {% endblock head_meta %}
    <style></style>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous"
    />
  </head>
  <link
    href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css"
    rel="stylesheet"
    type="text/css"
  />
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
  <body>
    {# Navigation Menu #}
    <header>
      <nav
        class="navbar navbar-dark bg-dark navbar-expand-lg px-5 {% block nav-style %}{% endblock %}"
      >
        <div class="container-fluid">
          <a class="navbar-brand" href="/">SILAU</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'silau:index' %}">Home</a>
              </li>
            </ul>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Testimoni
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% if request.session.pengguna.is_pelanggan %}
                  <a class="dropdown-item" href="{% url 'testimoni:index' page=0 %}">Read</a>
                  <a class="dropdown-item" href="{% url 'testimoni:add' %}">Add Testimoni</a>
                {% else %}
                    <a class="dropdown-item" href="{% url 'testimoni:other' page=0 %}">Read</a>
                {% endif %}
              </div>
            </div>
          </div>

          <div class="nav-item dropdown dropdown-menu-right" style="margin-right:6rem;">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% if request.session.pengguna %} Halo, {{request.session.pengguna.nama_lengkap}} ! {% else %} Akun {% endif %}
            </button>
            <div class="dropdown-menu" aria-labelledby="accountDropdown">
              {% if request.session.pengguna %}
              <a class="dropdown-item" href="{% url 'silau:logout2' %}">Logout</a>
              {% else %}
              <a class="dropdown-item" href="{% url 'silau:login2' %}">Login</a>
              <a class="dropdown-item" href="{% url 'silau:register_staff2' %}">Daftar sebagai Staff</a>
              <a class="dropdown-item" href="{% url 'silau:register_courier2' %}">Daftar sebagai Kurir</a>
              <a class="dropdown-item" href="/register/customer">Daftar sebagai Pelanggan (old)</a>
              {% endif %}
            <div>
          </div>
        </div>
      </nav>
    </header>
    {# The Document Body #}
    <div id="site-wrapper">
      {% block content %} if you see this, something is wrong! {% endblock content %}
    </div>
    {# The Footer #}
    <div class="footer"></div>
    {# Set of blocks that can be used to display JavaScript files #}
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/cash/8.1.0/cash.min.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
      $(document).ready(function(){
        $(".dropdown-toggle").dropdown();
      });
    </script>
    {% block js %} 
    {% endblock js %}
  </body>
</html>